issues:
  exclude-dirs:
    - ".*\\.pb*"
linters-settings:
  lll:
    line-length: 140
linters:
  enable-all: true
  disable:
    - exportloopref
    - tagalign
    - bodyclose
    - depguard
    - exhaustruct
    - forcetypeassert
    - gochecknoglobals
    - ireturn
    - paralleltest
    - varnamelen
    - wrapcheck
