# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: standort/v2/service.proto for package 'Standort.V2'

require 'grpc'
require 'standort/v2/service_pb'

module Standort
  module V2
    module Service
      # Service allows to get location via multiple methods.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'standort.v2.Service'

        # GetLocation via multiple methods.
        rpc :GetLocation, ::Standort::V2::GetLocationRequest, ::Standort::V2::GetLocationResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
