# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: standort/v2/service.proto for package 'Standort.V2'

require 'grpc'
require 'standort/v2/service_pb'

module Standort
  module V2
    module Service
      # Service allows to get location via multiple methods.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'standort.v2.Service'

        # GetLocation resolves an IP address and/or geographic point. If one lookup
        # succeeds, the response is successful. Returns gRPC NotFound only when no
        # lookup succeeds; v2 transports may attach code-only diagnostics to the
        # terminal error metadata.
        rpc :GetLocation, ::Standort::V2::GetLocationRequest, ::Standort::V2::GetLocationResponse
        # LookupLocations resolves multiple location lookups, preserving request order.
        # Missing entry inputs may fall back to request metadata for each entry.
        rpc :LookupLocations, ::Standort::V2::LookupLocationsRequest, ::Standort::V2::LookupLocationsResponse
        # GetLookupAssets returns metadata for embedded lookup assets.
        rpc :GetLookupAssets, ::Standort::V2::GetLookupAssetsRequest, ::Standort::V2::GetLookupAssetsResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
