// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: standort/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	// GetLocationByIP for an IP address.
	GetLocationByIP(ctx context.Context, in *GetLocationByIPRequest, opts ...grpc.CallOption) (*GetLocationByIPResponse, error)
	// GetLocationByLatLng for a latitude and longitude.
	GetLocationByLatLng(ctx context.Context, in *GetLocationByLatLngRequest, opts ...grpc.CallOption) (*GetLocationByLatLngResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) GetLocationByIP(ctx context.Context, in *GetLocationByIPRequest, opts ...grpc.CallOption) (*GetLocationByIPResponse, error) {
	out := new(GetLocationByIPResponse)
	err := c.cc.Invoke(ctx, "/standort.v1.Service/GetLocationByIP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetLocationByLatLng(ctx context.Context, in *GetLocationByLatLngRequest, opts ...grpc.CallOption) (*GetLocationByLatLngResponse, error) {
	out := new(GetLocationByLatLngResponse)
	err := c.cc.Invoke(ctx, "/standort.v1.Service/GetLocationByLatLng", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	// GetLocationByIP for an IP address.
	GetLocationByIP(context.Context, *GetLocationByIPRequest) (*GetLocationByIPResponse, error)
	// GetLocationByLatLng for a latitude and longitude.
	GetLocationByLatLng(context.Context, *GetLocationByLatLngRequest) (*GetLocationByLatLngResponse, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) GetLocationByIP(context.Context, *GetLocationByIPRequest) (*GetLocationByIPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocationByIP not implemented")
}
func (UnimplementedServiceServer) GetLocationByLatLng(context.Context, *GetLocationByLatLngRequest) (*GetLocationByLatLngResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocationByLatLng not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_GetLocationByIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocationByIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetLocationByIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standort.v1.Service/GetLocationByIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetLocationByIP(ctx, req.(*GetLocationByIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetLocationByLatLng_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocationByLatLngRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetLocationByLatLng(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/standort.v1.Service/GetLocationByLatLng",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetLocationByLatLng(ctx, req.(*GetLocationByLatLngRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "standort.v1.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLocationByIP",
			Handler:    _Service_GetLocationByIP_Handler,
		},
		{
			MethodName: "GetLocationByLatLng",
			Handler:    _Service_GetLocationByLatLng_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "standort/v1/service.proto",
}
