// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: standort/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Location of the response.
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Continent     string                 `protobuf:"bytes,2,opt,name=continent,proto3" json:"continent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_standort_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_standort_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Location) GetContinent() string {
	if x != nil {
		return x.Continent
	}
	return ""
}

// GetLocationByIPRequest for an IP address.
type GetLocationByIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationByIPRequest) Reset() {
	*x = GetLocationByIPRequest{}
	mi := &file_standort_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationByIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationByIPRequest) ProtoMessage() {}

func (x *GetLocationByIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationByIPRequest.ProtoReflect.Descriptor instead.
func (*GetLocationByIPRequest) Descriptor() ([]byte, []int) {
	return file_standort_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetLocationByIPRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// GetLocationByIPResponse for an IP address.
type GetLocationByIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          map[string]string      `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Location      *Location              `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationByIPResponse) Reset() {
	*x = GetLocationByIPResponse{}
	mi := &file_standort_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationByIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationByIPResponse) ProtoMessage() {}

func (x *GetLocationByIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationByIPResponse.ProtoReflect.Descriptor instead.
func (*GetLocationByIPResponse) Descriptor() ([]byte, []int) {
	return file_standort_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetLocationByIPResponse) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetLocationByIPResponse) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

// GetLocationByLatLngRequest for a latitude and longitude.
type GetLocationByLatLngRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationByLatLngRequest) Reset() {
	*x = GetLocationByLatLngRequest{}
	mi := &file_standort_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationByLatLngRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationByLatLngRequest) ProtoMessage() {}

func (x *GetLocationByLatLngRequest) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationByLatLngRequest.ProtoReflect.Descriptor instead.
func (*GetLocationByLatLngRequest) Descriptor() ([]byte, []int) {
	return file_standort_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetLocationByLatLngRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GetLocationByLatLngRequest) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

// GetLocationByLatLngResponse for a latitude and longitude.
type GetLocationByLatLngResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          map[string]string      `protobuf:"bytes,2,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationByLatLngResponse) Reset() {
	*x = GetLocationByLatLngResponse{}
	mi := &file_standort_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationByLatLngResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationByLatLngResponse) ProtoMessage() {}

func (x *GetLocationByLatLngResponse) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationByLatLngResponse.ProtoReflect.Descriptor instead.
func (*GetLocationByLatLngResponse) Descriptor() ([]byte, []int) {
	return file_standort_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetLocationByLatLngResponse) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetLocationByLatLngResponse) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

var File_standort_v1_service_proto protoreflect.FileDescriptor

const file_standort_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x19standort/v1/service.proto\x12\vstandort.v1\"B\n" +
	"\bLocation\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x1c\n" +
	"\tcontinent\x18\x02 \x01(\tR\tcontinent\"(\n" +
	"\x16GetLocationByIPRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"\xc9\x01\n" +
	"\x17GetLocationByIPResponse\x12B\n" +
	"\x04meta\x18\x01 \x03(\v2..standort.v1.GetLocationByIPResponse.MetaEntryR\x04meta\x121\n" +
	"\blocation\x18\x02 \x01(\v2\x15.standort.v1.LocationR\blocation\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x1aGetLocationByLatLngRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\"\xd1\x01\n" +
	"\x1bGetLocationByLatLngResponse\x12F\n" +
	"\x04meta\x18\x02 \x03(\v22.standort.v1.GetLocationByLatLngResponse.MetaEntryR\x04meta\x121\n" +
	"\blocation\x18\x01 \x01(\v2\x15.standort.v1.LocationR\blocation\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xd5\x01\n" +
	"\aService\x12^\n" +
	"\x0fGetLocationByIP\x12#.standort.v1.GetLocationByIPRequest\x1a$.standort.v1.GetLocationByIPResponse\"\x00\x12j\n" +
	"\x13GetLocationByLatLng\x12'.standort.v1.GetLocationByLatLngRequest\x1a(.standort.v1.GetLocationByLatLngResponse\"\x00BEZ4github.com/alexfalkowski/standort/v2/api/standort/v1\xea\x02\fStandort::V1b\x06proto3"

var (
	file_standort_v1_service_proto_rawDescOnce sync.Once
	file_standort_v1_service_proto_rawDescData []byte
)

func file_standort_v1_service_proto_rawDescGZIP() []byte {
	file_standort_v1_service_proto_rawDescOnce.Do(func() {
		file_standort_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_standort_v1_service_proto_rawDesc), len(file_standort_v1_service_proto_rawDesc)))
	})
	return file_standort_v1_service_proto_rawDescData
}

var file_standort_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_standort_v1_service_proto_goTypes = []any{
	(*Location)(nil),                    // 0: standort.v1.Location
	(*GetLocationByIPRequest)(nil),      // 1: standort.v1.GetLocationByIPRequest
	(*GetLocationByIPResponse)(nil),     // 2: standort.v1.GetLocationByIPResponse
	(*GetLocationByLatLngRequest)(nil),  // 3: standort.v1.GetLocationByLatLngRequest
	(*GetLocationByLatLngResponse)(nil), // 4: standort.v1.GetLocationByLatLngResponse
	nil,                                 // 5: standort.v1.GetLocationByIPResponse.MetaEntry
	nil,                                 // 6: standort.v1.GetLocationByLatLngResponse.MetaEntry
}
var file_standort_v1_service_proto_depIdxs = []int32{
	5, // 0: standort.v1.GetLocationByIPResponse.meta:type_name -> standort.v1.GetLocationByIPResponse.MetaEntry
	0, // 1: standort.v1.GetLocationByIPResponse.location:type_name -> standort.v1.Location
	6, // 2: standort.v1.GetLocationByLatLngResponse.meta:type_name -> standort.v1.GetLocationByLatLngResponse.MetaEntry
	0, // 3: standort.v1.GetLocationByLatLngResponse.location:type_name -> standort.v1.Location
	1, // 4: standort.v1.Service.GetLocationByIP:input_type -> standort.v1.GetLocationByIPRequest
	3, // 5: standort.v1.Service.GetLocationByLatLng:input_type -> standort.v1.GetLocationByLatLngRequest
	2, // 6: standort.v1.Service.GetLocationByIP:output_type -> standort.v1.GetLocationByIPResponse
	4, // 7: standort.v1.Service.GetLocationByLatLng:output_type -> standort.v1.GetLocationByLatLngResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_standort_v1_service_proto_init() }
func file_standort_v1_service_proto_init() {
	if File_standort_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_standort_v1_service_proto_rawDesc), len(file_standort_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_standort_v1_service_proto_goTypes,
		DependencyIndexes: file_standort_v1_service_proto_depIdxs,
		MessageInfos:      file_standort_v1_service_proto_msgTypes,
	}.Build()
	File_standort_v1_service_proto = out.File
	file_standort_v1_service_proto_goTypes = nil
	file_standort_v1_service_proto_depIdxs = nil
}
