// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: standort/v1/service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Location of the response.
type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country   string `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Continent string `protobuf:"bytes,2,opt,name=continent,proto3" json:"continent,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_standort_v1_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v1_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_standort_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Location) GetContinent() string {
	if x != nil {
		return x.Continent
	}
	return ""
}

// GetLocationByIPRequest for an IP address.
type GetLocationByIPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *GetLocationByIPRequest) Reset() {
	*x = GetLocationByIPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_standort_v1_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLocationByIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationByIPRequest) ProtoMessage() {}

func (x *GetLocationByIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v1_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationByIPRequest.ProtoReflect.Descriptor instead.
func (*GetLocationByIPRequest) Descriptor() ([]byte, []int) {
	return file_standort_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetLocationByIPRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// GetLocationByIPResponse for an IP address.
type GetLocationByIPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location *Location `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *GetLocationByIPResponse) Reset() {
	*x = GetLocationByIPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_standort_v1_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLocationByIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationByIPResponse) ProtoMessage() {}

func (x *GetLocationByIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v1_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationByIPResponse.ProtoReflect.Descriptor instead.
func (*GetLocationByIPResponse) Descriptor() ([]byte, []int) {
	return file_standort_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetLocationByIPResponse) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

// GetLocationByLatLngRequest for a latitude and longitude.
type GetLocationByLatLngRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng float64 `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
}

func (x *GetLocationByLatLngRequest) Reset() {
	*x = GetLocationByLatLngRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_standort_v1_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLocationByLatLngRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationByLatLngRequest) ProtoMessage() {}

func (x *GetLocationByLatLngRequest) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v1_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationByLatLngRequest.ProtoReflect.Descriptor instead.
func (*GetLocationByLatLngRequest) Descriptor() ([]byte, []int) {
	return file_standort_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetLocationByLatLngRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GetLocationByLatLngRequest) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

// GetLocationByLatLngResponse for a latitude and longitude.
type GetLocationByLatLngResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location *Location `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *GetLocationByLatLngResponse) Reset() {
	*x = GetLocationByLatLngResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_standort_v1_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLocationByLatLngResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationByLatLngResponse) ProtoMessage() {}

func (x *GetLocationByLatLngResponse) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v1_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationByLatLngResponse.ProtoReflect.Descriptor instead.
func (*GetLocationByLatLngResponse) Descriptor() ([]byte, []int) {
	return file_standort_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetLocationByLatLngResponse) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

var File_standort_v1_service_proto protoreflect.FileDescriptor

var file_standort_v1_service_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x6f, 0x72, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x74, 0x61,
	0x6e, 0x64, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6e, 0x74, 0x22, 0x28, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x50, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x70, 0x22, 0x4c, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x31, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x40, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x42, 0x79, 0x4c, 0x61, 0x74, 0x4c, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c,
	0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x03, 0x6c, 0x6e, 0x67, 0x22, 0x50, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x79, 0x4c, 0x61, 0x74, 0x4c, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x6f, 0x72, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x9a, 0x02, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x7a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x42, 0x79, 0x49, 0x50, 0x12, 0x23, 0x2e, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x6f, 0x72, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42,
	0x79, 0x49, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73, 0x74, 0x61,
	0x6e, 0x64, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x12, 0x14, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x69, 0x70, 0x2f, 0x7b, 0x69, 0x70, 0x7d, 0x12, 0x92,
	0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79,
	0x4c, 0x61, 0x74, 0x4c, 0x6e, 0x67, 0x12, 0x27, 0x2e, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x6f, 0x72,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x42, 0x79, 0x4c, 0x61, 0x74, 0x4c, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x28, 0x2e, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x4c, 0x61, 0x74, 0x4c, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x28, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x22, 0x12, 0x20, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x6c, 0x61, 0x74, 0x2f, 0x7b, 0x6c, 0x61, 0x74, 0x7d, 0x2f, 0x6c, 0x6e, 0x67, 0x2f, 0x7b, 0x6c,
	0x6e, 0x67, 0x7d, 0x42, 0x42, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x6c, 0x65, 0x78, 0x66, 0x61, 0x6c, 0x6b, 0x6f, 0x77, 0x73, 0x6b, 0x69, 0x2f,
	0x73, 0x74, 0x61, 0x6e, 0x64, 0x6f, 0x72, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x61,
	0x6e, 0x64, 0x6f, 0x72, 0x74, 0x2f, 0x76, 0x31, 0xea, 0x02, 0x0c, 0x53, 0x74, 0x61, 0x6e, 0x64,
	0x6f, 0x72, 0x74, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_standort_v1_service_proto_rawDescOnce sync.Once
	file_standort_v1_service_proto_rawDescData = file_standort_v1_service_proto_rawDesc
)

func file_standort_v1_service_proto_rawDescGZIP() []byte {
	file_standort_v1_service_proto_rawDescOnce.Do(func() {
		file_standort_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_standort_v1_service_proto_rawDescData)
	})
	return file_standort_v1_service_proto_rawDescData
}

var file_standort_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_standort_v1_service_proto_goTypes = []interface{}{
	(*Location)(nil),                    // 0: standort.v1.Location
	(*GetLocationByIPRequest)(nil),      // 1: standort.v1.GetLocationByIPRequest
	(*GetLocationByIPResponse)(nil),     // 2: standort.v1.GetLocationByIPResponse
	(*GetLocationByLatLngRequest)(nil),  // 3: standort.v1.GetLocationByLatLngRequest
	(*GetLocationByLatLngResponse)(nil), // 4: standort.v1.GetLocationByLatLngResponse
}
var file_standort_v1_service_proto_depIdxs = []int32{
	0, // 0: standort.v1.GetLocationByIPResponse.location:type_name -> standort.v1.Location
	0, // 1: standort.v1.GetLocationByLatLngResponse.location:type_name -> standort.v1.Location
	1, // 2: standort.v1.Service.GetLocationByIP:input_type -> standort.v1.GetLocationByIPRequest
	3, // 3: standort.v1.Service.GetLocationByLatLng:input_type -> standort.v1.GetLocationByLatLngRequest
	2, // 4: standort.v1.Service.GetLocationByIP:output_type -> standort.v1.GetLocationByIPResponse
	4, // 5: standort.v1.Service.GetLocationByLatLng:output_type -> standort.v1.GetLocationByLatLngResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_standort_v1_service_proto_init() }
func file_standort_v1_service_proto_init() {
	if File_standort_v1_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_standort_v1_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_standort_v1_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLocationByIPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_standort_v1_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLocationByIPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_standort_v1_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLocationByLatLngRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_standort_v1_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLocationByLatLngResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_standort_v1_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_standort_v1_service_proto_goTypes,
		DependencyIndexes: file_standort_v1_service_proto_depIdxs,
		MessageInfos:      file_standort_v1_service_proto_msgTypes,
	}.Build()
	File_standort_v1_service_proto = out.File
	file_standort_v1_service_proto_rawDesc = nil
	file_standort_v1_service_proto_goTypes = nil
	file_standort_v1_service_proto_depIdxs = nil
}
