version: 2.1

jobs:
  build:
    docker:
      - image: alexfalkowski/go:1.19-3.1
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: make dep
      - run: make lint
      - run: make sec
      - run: make features
      - run: make goveralls
      - store_artifacts:
          path: test/reports
  release:
    docker:
      - image: alexfalkowski/release:3.1
    steps:
      - checkout
      - run: release
  docker:
    docker:
      - image: alexfalkowski/go:1.19-3.1
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make docker

workflows:
  standort:
    jobs:
      - build
      - release:
          context: gh
          requires:
            - build
          filters:
            branches:
              only: master
      - docker:
          context: docker
          requires:
            - release
          filters:
            branches:
              only: master
