// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: standort/v2/service.proto

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Service_GetLocation_FullMethodName     = "/standort.v2.Service/GetLocation"
	Service_LookupLocations_FullMethodName = "/standort.v2.Service/LookupLocations"
	Service_GetLookupAssets_FullMethodName = "/standort.v2.Service/GetLookupAssets"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service allows to get location via multiple methods.
type ServiceClient interface {
	// GetLocation resolves an IP address and/or geographic point. If one lookup
	// succeeds, the response is successful. Returns gRPC NotFound only when no
	// lookup succeeds; v2 transports may attach code-only diagnostics to the
	// terminal error metadata.
	GetLocation(ctx context.Context, in *GetLocationRequest, opts ...grpc.CallOption) (*GetLocationResponse, error)
	// LookupLocations resolves multiple location lookups, preserving request order.
	// Missing entry inputs may fall back to request metadata for each entry.
	LookupLocations(ctx context.Context, in *LookupLocationsRequest, opts ...grpc.CallOption) (*LookupLocationsResponse, error)
	// GetLookupAssets returns metadata for embedded lookup assets.
	GetLookupAssets(ctx context.Context, in *GetLookupAssetsRequest, opts ...grpc.CallOption) (*GetLookupAssetsResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) GetLocation(ctx context.Context, in *GetLocationRequest, opts ...grpc.CallOption) (*GetLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLocationResponse)
	err := c.cc.Invoke(ctx, Service_GetLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) LookupLocations(ctx context.Context, in *LookupLocationsRequest, opts ...grpc.CallOption) (*LookupLocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupLocationsResponse)
	err := c.cc.Invoke(ctx, Service_LookupLocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetLookupAssets(ctx context.Context, in *GetLookupAssetsRequest, opts ...grpc.CallOption) (*GetLookupAssetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLookupAssetsResponse)
	err := c.cc.Invoke(ctx, Service_GetLookupAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility.
//
// Service allows to get location via multiple methods.
type ServiceServer interface {
	// GetLocation resolves an IP address and/or geographic point. If one lookup
	// succeeds, the response is successful. Returns gRPC NotFound only when no
	// lookup succeeds; v2 transports may attach code-only diagnostics to the
	// terminal error metadata.
	GetLocation(context.Context, *GetLocationRequest) (*GetLocationResponse, error)
	// LookupLocations resolves multiple location lookups, preserving request order.
	// Missing entry inputs may fall back to request metadata for each entry.
	LookupLocations(context.Context, *LookupLocationsRequest) (*LookupLocationsResponse, error)
	// GetLookupAssets returns metadata for embedded lookup assets.
	GetLookupAssets(context.Context, *GetLookupAssetsRequest) (*GetLookupAssetsResponse, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceServer struct{}

func (UnimplementedServiceServer) GetLocation(context.Context, *GetLocationRequest) (*GetLocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLocation not implemented")
}
func (UnimplementedServiceServer) LookupLocations(context.Context, *LookupLocationsRequest) (*LookupLocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupLocations not implemented")
}
func (UnimplementedServiceServer) GetLookupAssets(context.Context, *GetLookupAssetsRequest) (*GetLookupAssetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLookupAssets not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}
func (UnimplementedServiceServer) testEmbeddedByValue()                 {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	// If the following call panics, it indicates UnimplementedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_GetLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetLocation(ctx, req.(*GetLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_LookupLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).LookupLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_LookupLocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).LookupLocations(ctx, req.(*LookupLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetLookupAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLookupAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetLookupAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetLookupAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetLookupAssets(ctx, req.(*GetLookupAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "standort.v2.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLocation",
			Handler:    _Service_GetLocation_Handler,
		},
		{
			MethodName: "LookupLocations",
			Handler:    _Service_LookupLocations_Handler,
		},
		{
			MethodName: "GetLookupAssets",
			Handler:    _Service_GetLookupAssets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "standort/v2/service.proto",
}
