// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: standort/v2/service.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Location of the response.
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Continent     string                 `protobuf:"bytes,2,opt,name=continent,proto3" json:"continent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_standort_v2_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v2_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_standort_v2_service_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Location) GetContinent() string {
	if x != nil {
		return x.Continent
	}
	return ""
}

// Point for the request.
type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_standort_v2_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v2_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_standort_v2_service_proto_rawDescGZIP(), []int{1}
}

func (x *Point) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Point) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

// GetLocationRequest for getting the location.
type GetLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Point         *Point                 `protobuf:"bytes,2,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationRequest) Reset() {
	*x = GetLocationRequest{}
	mi := &file_standort_v2_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationRequest) ProtoMessage() {}

func (x *GetLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v2_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationRequest.ProtoReflect.Descriptor instead.
func (*GetLocationRequest) Descriptor() ([]byte, []int) {
	return file_standort_v2_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetLocationRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *GetLocationRequest) GetPoint() *Point {
	if x != nil {
		return x.Point
	}
	return nil
}

// GetLocationResponse for getting the location.
type GetLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          map[string]string      `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ip            *Location              `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Geo           *Location              `protobuf:"bytes,3,opt,name=geo,proto3" json:"geo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationResponse) Reset() {
	*x = GetLocationResponse{}
	mi := &file_standort_v2_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationResponse) ProtoMessage() {}

func (x *GetLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v2_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationResponse.ProtoReflect.Descriptor instead.
func (*GetLocationResponse) Descriptor() ([]byte, []int) {
	return file_standort_v2_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetLocationResponse) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetLocationResponse) GetIp() *Location {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *GetLocationResponse) GetGeo() *Location {
	if x != nil {
		return x.Geo
	}
	return nil
}

var File_standort_v2_service_proto protoreflect.FileDescriptor

const file_standort_v2_service_proto_rawDesc = "" +
	"\n" +
	"\x19standort/v2/service.proto\x12\vstandort.v2\"B\n" +
	"\bLocation\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x1c\n" +
	"\tcontinent\x18\x02 \x01(\tR\tcontinent\"+\n" +
	"\x05Point\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\"N\n" +
	"\x12GetLocationRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12(\n" +
	"\x05point\x18\x02 \x01(\v2\x12.standort.v2.PointR\x05point\"\xde\x01\n" +
	"\x13GetLocationResponse\x12>\n" +
	"\x04meta\x18\x01 \x03(\v2*.standort.v2.GetLocationResponse.MetaEntryR\x04meta\x12%\n" +
	"\x02ip\x18\x02 \x01(\v2\x15.standort.v2.LocationR\x02ip\x12'\n" +
	"\x03geo\x18\x03 \x01(\v2\x15.standort.v2.LocationR\x03geo\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012]\n" +
	"\aService\x12R\n" +
	"\vGetLocation\x12\x1f.standort.v2.GetLocationRequest\x1a .standort.v2.GetLocationResponse\"\x00BEZ4github.com/alexfalkowski/standort/v2/api/standort/v2\xea\x02\fStandort::V2b\x06proto3"

var (
	file_standort_v2_service_proto_rawDescOnce sync.Once
	file_standort_v2_service_proto_rawDescData []byte
)

func file_standort_v2_service_proto_rawDescGZIP() []byte {
	file_standort_v2_service_proto_rawDescOnce.Do(func() {
		file_standort_v2_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_standort_v2_service_proto_rawDesc), len(file_standort_v2_service_proto_rawDesc)))
	})
	return file_standort_v2_service_proto_rawDescData
}

var file_standort_v2_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_standort_v2_service_proto_goTypes = []any{
	(*Location)(nil),            // 0: standort.v2.Location
	(*Point)(nil),               // 1: standort.v2.Point
	(*GetLocationRequest)(nil),  // 2: standort.v2.GetLocationRequest
	(*GetLocationResponse)(nil), // 3: standort.v2.GetLocationResponse
	nil,                         // 4: standort.v2.GetLocationResponse.MetaEntry
}
var file_standort_v2_service_proto_depIdxs = []int32{
	1, // 0: standort.v2.GetLocationRequest.point:type_name -> standort.v2.Point
	4, // 1: standort.v2.GetLocationResponse.meta:type_name -> standort.v2.GetLocationResponse.MetaEntry
	0, // 2: standort.v2.GetLocationResponse.ip:type_name -> standort.v2.Location
	0, // 3: standort.v2.GetLocationResponse.geo:type_name -> standort.v2.Location
	2, // 4: standort.v2.Service.GetLocation:input_type -> standort.v2.GetLocationRequest
	3, // 5: standort.v2.Service.GetLocation:output_type -> standort.v2.GetLocationResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_standort_v2_service_proto_init() }
func file_standort_v2_service_proto_init() {
	if File_standort_v2_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_standort_v2_service_proto_rawDesc), len(file_standort_v2_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_standort_v2_service_proto_goTypes,
		DependencyIndexes: file_standort_v2_service_proto_depIdxs,
		MessageInfos:      file_standort_v2_service_proto_msgTypes,
	}.Build()
	File_standort_v2_service_proto = out.File
	file_standort_v2_service_proto_goTypes = nil
	file_standort_v2_service_proto_depIdxs = nil
}
