// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: standort/v2/service.proto

package v2

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Location of the response.
type Location struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ISO-3166 alpha-2 country code, such as US or DE.
	Country string `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	// Two-letter continent code, such as NA or EU.
	Continent     string `protobuf:"bytes,2,opt,name=continent,proto3" json:"continent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_standort_v2_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v2_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_standort_v2_service_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Location) GetContinent() string {
	if x != nil {
		return x.Continent
	}
	return ""
}

// Point for the request.
type Point struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Latitude in degrees. Must be finite and in the range [-90, 90].
	Lat float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	// Longitude in degrees. Must be finite and in the range [-180, 180].
	Lng           float64 `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_standort_v2_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v2_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_standort_v2_service_proto_rawDescGZIP(), []int{1}
}

func (x *Point) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Point) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

// GetLocationRequest for getting the location.
type GetLocationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP address to resolve. If empty, the server may use request metadata such as X-Forwarded-For.
	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	// Geographic point to resolve. If omitted, the server may use a Geolocation metadata header.
	Point         *Point `protobuf:"bytes,2,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationRequest) Reset() {
	*x = GetLocationRequest{}
	mi := &file_standort_v2_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationRequest) ProtoMessage() {}

func (x *GetLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v2_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationRequest.ProtoReflect.Descriptor instead.
func (*GetLocationRequest) Descriptor() ([]byte, []int) {
	return file_standort_v2_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetLocationRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *GetLocationRequest) GetPoint() *Point {
	if x != nil {
		return x.Point
	}
	return nil
}

// GetLocationResponse for getting the location.
type GetLocationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Meta contains request metadata returned to the caller, such as requestId.
	Meta map[string]string `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// IP is populated when the IP lookup succeeds.
	Ip *Location `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	// Geo is populated when the point lookup succeeds.
	Geo           *Location `protobuf:"bytes,3,opt,name=geo,proto3" json:"geo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationResponse) Reset() {
	*x = GetLocationResponse{}
	mi := &file_standort_v2_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationResponse) ProtoMessage() {}

func (x *GetLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v2_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationResponse.ProtoReflect.Descriptor instead.
func (*GetLocationResponse) Descriptor() ([]byte, []int) {
	return file_standort_v2_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetLocationResponse) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetLocationResponse) GetIp() *Location {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *GetLocationResponse) GetGeo() *Location {
	if x != nil {
		return x.Geo
	}
	return nil
}

// LocationLookup is one lookup entry for a batch request.
type LocationLookup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP address to resolve. If empty, the server may use request metadata such
	// as X-Forwarded-For for this entry.
	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	// Geographic point to resolve. If omitted, the server may use a Geolocation
	// metadata header for this entry.
	Point         *Point `protobuf:"bytes,2,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationLookup) Reset() {
	*x = LocationLookup{}
	mi := &file_standort_v2_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationLookup) ProtoMessage() {}

func (x *LocationLookup) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v2_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationLookup.ProtoReflect.Descriptor instead.
func (*LocationLookup) Descriptor() ([]byte, []int) {
	return file_standort_v2_service_proto_rawDescGZIP(), []int{4}
}

func (x *LocationLookup) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *LocationLookup) GetPoint() *Point {
	if x != nil {
		return x.Point
	}
	return nil
}

// LookupLocationsRequest for batch location lookup.
type LookupLocationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Lookups contains the entries to resolve. At most 100 lookups are supported;
	// larger requests fail the whole call with gRPC InvalidArgument.
	Lookups       []*LocationLookup `protobuf:"bytes,1,rep,name=lookups,proto3" json:"lookups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupLocationsRequest) Reset() {
	*x = LookupLocationsRequest{}
	mi := &file_standort_v2_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupLocationsRequest) ProtoMessage() {}

func (x *LookupLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v2_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupLocationsRequest.ProtoReflect.Descriptor instead.
func (*LookupLocationsRequest) Descriptor() ([]byte, []int) {
	return file_standort_v2_service_proto_rawDescGZIP(), []int{5}
}

func (x *LookupLocationsRequest) GetLookups() []*LocationLookup {
	if x != nil {
		return x.Lookups
	}
	return nil
}

// LocationLookupResponse is one lookup entry in a batch response.
type LocationLookupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP is populated when the IP lookup succeeds.
	Ip *Location `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	// Geo is populated when the point lookup succeeds.
	Geo *Location `protobuf:"bytes,2,opt,name=geo,proto3" json:"geo,omitempty"`
	// Status is populated when this lookup does not resolve any location.
	Status        *status.Status `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationLookupResponse) Reset() {
	*x = LocationLookupResponse{}
	mi := &file_standort_v2_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationLookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationLookupResponse) ProtoMessage() {}

func (x *LocationLookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v2_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationLookupResponse.ProtoReflect.Descriptor instead.
func (*LocationLookupResponse) Descriptor() ([]byte, []int) {
	return file_standort_v2_service_proto_rawDescGZIP(), []int{6}
}

func (x *LocationLookupResponse) GetIp() *Location {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *LocationLookupResponse) GetGeo() *Location {
	if x != nil {
		return x.Geo
	}
	return nil
}

func (x *LocationLookupResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// LookupLocationsResponse for batch location lookup.
type LookupLocationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Meta contains request metadata returned to the caller, such as requestId.
	Meta map[string]string `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Lookups contains one response for each request lookup, preserving order.
	Lookups       []*LocationLookupResponse `protobuf:"bytes,2,rep,name=lookups,proto3" json:"lookups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupLocationsResponse) Reset() {
	*x = LookupLocationsResponse{}
	mi := &file_standort_v2_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupLocationsResponse) ProtoMessage() {}

func (x *LookupLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v2_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupLocationsResponse.ProtoReflect.Descriptor instead.
func (*LookupLocationsResponse) Descriptor() ([]byte, []int) {
	return file_standort_v2_service_proto_rawDescGZIP(), []int{7}
}

func (x *LookupLocationsResponse) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *LookupLocationsResponse) GetLookups() []*LocationLookupResponse {
	if x != nil {
		return x.Lookups
	}
	return nil
}

// GetLookupAssetsRequest for embedded lookup asset metadata.
type GetLookupAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLookupAssetsRequest) Reset() {
	*x = GetLookupAssetsRequest{}
	mi := &file_standort_v2_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLookupAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLookupAssetsRequest) ProtoMessage() {}

func (x *GetLookupAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v2_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLookupAssetsRequest.ProtoReflect.Descriptor instead.
func (*GetLookupAssetsRequest) Descriptor() ([]byte, []int) {
	return file_standort_v2_service_proto_rawDescGZIP(), []int{8}
}

// LookupAsset describes one embedded lookup asset.
type LookupAsset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the embedded asset filename.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// SizeBytes is the embedded asset size in bytes.
	SizeBytes uint64 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// ChecksumAlgorithm identifies the checksum algorithm used for Checksum.
	ChecksumAlgorithm string `protobuf:"bytes,3,opt,name=checksum_algorithm,json=checksumAlgorithm,proto3" json:"checksum_algorithm,omitempty"`
	// Checksum is the lowercase hexadecimal checksum of the embedded asset.
	Checksum      string `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupAsset) Reset() {
	*x = LookupAsset{}
	mi := &file_standort_v2_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupAsset) ProtoMessage() {}

func (x *LookupAsset) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v2_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupAsset.ProtoReflect.Descriptor instead.
func (*LookupAsset) Descriptor() ([]byte, []int) {
	return file_standort_v2_service_proto_rawDescGZIP(), []int{9}
}

func (x *LookupAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LookupAsset) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *LookupAsset) GetChecksumAlgorithm() string {
	if x != nil {
		return x.ChecksumAlgorithm
	}
	return ""
}

func (x *LookupAsset) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

// GetLookupAssetsResponse for embedded lookup asset metadata.
type GetLookupAssetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Meta contains request metadata returned to the caller, such as requestId.
	Meta map[string]string `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Assets contains metadata for the embedded lookup assets.
	Assets        []*LookupAsset `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLookupAssetsResponse) Reset() {
	*x = GetLookupAssetsResponse{}
	mi := &file_standort_v2_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLookupAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLookupAssetsResponse) ProtoMessage() {}

func (x *GetLookupAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_standort_v2_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLookupAssetsResponse.ProtoReflect.Descriptor instead.
func (*GetLookupAssetsResponse) Descriptor() ([]byte, []int) {
	return file_standort_v2_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetLookupAssetsResponse) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetLookupAssetsResponse) GetAssets() []*LookupAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

var File_standort_v2_service_proto protoreflect.FileDescriptor

const file_standort_v2_service_proto_rawDesc = "" +
	"\n" +
	"\x19standort/v2/service.proto\x12\vstandort.v2\x1a\x17google/rpc/status.proto\"B\n" +
	"\bLocation\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x1c\n" +
	"\tcontinent\x18\x02 \x01(\tR\tcontinent\"+\n" +
	"\x05Point\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\"N\n" +
	"\x12GetLocationRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12(\n" +
	"\x05point\x18\x02 \x01(\v2\x12.standort.v2.PointR\x05point\"\xde\x01\n" +
	"\x13GetLocationResponse\x12>\n" +
	"\x04meta\x18\x01 \x03(\v2*.standort.v2.GetLocationResponse.MetaEntryR\x04meta\x12%\n" +
	"\x02ip\x18\x02 \x01(\v2\x15.standort.v2.LocationR\x02ip\x12'\n" +
	"\x03geo\x18\x03 \x01(\v2\x15.standort.v2.LocationR\x03geo\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"J\n" +
	"\x0eLocationLookup\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12(\n" +
	"\x05point\x18\x02 \x01(\v2\x12.standort.v2.PointR\x05point\"O\n" +
	"\x16LookupLocationsRequest\x125\n" +
	"\alookups\x18\x01 \x03(\v2\x1b.standort.v2.LocationLookupR\alookups\"\x94\x01\n" +
	"\x16LocationLookupResponse\x12%\n" +
	"\x02ip\x18\x01 \x01(\v2\x15.standort.v2.LocationR\x02ip\x12'\n" +
	"\x03geo\x18\x02 \x01(\v2\x15.standort.v2.LocationR\x03geo\x12*\n" +
	"\x06status\x18\x03 \x01(\v2\x12.google.rpc.StatusR\x06status\"\xd5\x01\n" +
	"\x17LookupLocationsResponse\x12B\n" +
	"\x04meta\x18\x01 \x03(\v2..standort.v2.LookupLocationsResponse.MetaEntryR\x04meta\x12=\n" +
	"\alookups\x18\x02 \x03(\v2#.standort.v2.LocationLookupResponseR\alookups\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x18\n" +
	"\x16GetLookupAssetsRequest\"\x8b\x01\n" +
	"\vLookupAsset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x04R\tsizeBytes\x12-\n" +
	"\x12checksum_algorithm\x18\x03 \x01(\tR\x11checksumAlgorithm\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\"\xc8\x01\n" +
	"\x17GetLookupAssetsResponse\x12B\n" +
	"\x04meta\x18\x01 \x03(\v2..standort.v2.GetLookupAssetsResponse.MetaEntryR\x04meta\x120\n" +
	"\x06assets\x18\x02 \x03(\v2\x18.standort.v2.LookupAssetR\x06assets\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x9d\x02\n" +
	"\aService\x12R\n" +
	"\vGetLocation\x12\x1f.standort.v2.GetLocationRequest\x1a .standort.v2.GetLocationResponse\"\x00\x12^\n" +
	"\x0fLookupLocations\x12#.standort.v2.LookupLocationsRequest\x1a$.standort.v2.LookupLocationsResponse\"\x00\x12^\n" +
	"\x0fGetLookupAssets\x12#.standort.v2.GetLookupAssetsRequest\x1a$.standort.v2.GetLookupAssetsResponse\"\x00BEZ4github.com/alexfalkowski/standort/v2/api/standort/v2\xea\x02\fStandort::V2b\x06proto3"

var (
	file_standort_v2_service_proto_rawDescOnce sync.Once
	file_standort_v2_service_proto_rawDescData []byte
)

func file_standort_v2_service_proto_rawDescGZIP() []byte {
	file_standort_v2_service_proto_rawDescOnce.Do(func() {
		file_standort_v2_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_standort_v2_service_proto_rawDesc), len(file_standort_v2_service_proto_rawDesc)))
	})
	return file_standort_v2_service_proto_rawDescData
}

var file_standort_v2_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_standort_v2_service_proto_goTypes = []any{
	(*Location)(nil),                // 0: standort.v2.Location
	(*Point)(nil),                   // 1: standort.v2.Point
	(*GetLocationRequest)(nil),      // 2: standort.v2.GetLocationRequest
	(*GetLocationResponse)(nil),     // 3: standort.v2.GetLocationResponse
	(*LocationLookup)(nil),          // 4: standort.v2.LocationLookup
	(*LookupLocationsRequest)(nil),  // 5: standort.v2.LookupLocationsRequest
	(*LocationLookupResponse)(nil),  // 6: standort.v2.LocationLookupResponse
	(*LookupLocationsResponse)(nil), // 7: standort.v2.LookupLocationsResponse
	(*GetLookupAssetsRequest)(nil),  // 8: standort.v2.GetLookupAssetsRequest
	(*LookupAsset)(nil),             // 9: standort.v2.LookupAsset
	(*GetLookupAssetsResponse)(nil), // 10: standort.v2.GetLookupAssetsResponse
	nil,                             // 11: standort.v2.GetLocationResponse.MetaEntry
	nil,                             // 12: standort.v2.LookupLocationsResponse.MetaEntry
	nil,                             // 13: standort.v2.GetLookupAssetsResponse.MetaEntry
	(*status.Status)(nil),           // 14: google.rpc.Status
}
var file_standort_v2_service_proto_depIdxs = []int32{
	1,  // 0: standort.v2.GetLocationRequest.point:type_name -> standort.v2.Point
	11, // 1: standort.v2.GetLocationResponse.meta:type_name -> standort.v2.GetLocationResponse.MetaEntry
	0,  // 2: standort.v2.GetLocationResponse.ip:type_name -> standort.v2.Location
	0,  // 3: standort.v2.GetLocationResponse.geo:type_name -> standort.v2.Location
	1,  // 4: standort.v2.LocationLookup.point:type_name -> standort.v2.Point
	4,  // 5: standort.v2.LookupLocationsRequest.lookups:type_name -> standort.v2.LocationLookup
	0,  // 6: standort.v2.LocationLookupResponse.ip:type_name -> standort.v2.Location
	0,  // 7: standort.v2.LocationLookupResponse.geo:type_name -> standort.v2.Location
	14, // 8: standort.v2.LocationLookupResponse.status:type_name -> google.rpc.Status
	12, // 9: standort.v2.LookupLocationsResponse.meta:type_name -> standort.v2.LookupLocationsResponse.MetaEntry
	6,  // 10: standort.v2.LookupLocationsResponse.lookups:type_name -> standort.v2.LocationLookupResponse
	13, // 11: standort.v2.GetLookupAssetsResponse.meta:type_name -> standort.v2.GetLookupAssetsResponse.MetaEntry
	9,  // 12: standort.v2.GetLookupAssetsResponse.assets:type_name -> standort.v2.LookupAsset
	2,  // 13: standort.v2.Service.GetLocation:input_type -> standort.v2.GetLocationRequest
	5,  // 14: standort.v2.Service.LookupLocations:input_type -> standort.v2.LookupLocationsRequest
	8,  // 15: standort.v2.Service.GetLookupAssets:input_type -> standort.v2.GetLookupAssetsRequest
	3,  // 16: standort.v2.Service.GetLocation:output_type -> standort.v2.GetLocationResponse
	7,  // 17: standort.v2.Service.LookupLocations:output_type -> standort.v2.LookupLocationsResponse
	10, // 18: standort.v2.Service.GetLookupAssets:output_type -> standort.v2.GetLookupAssetsResponse
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_standort_v2_service_proto_init() }
func file_standort_v2_service_proto_init() {
	if File_standort_v2_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_standort_v2_service_proto_rawDesc), len(file_standort_v2_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_standort_v2_service_proto_goTypes,
		DependencyIndexes: file_standort_v2_service_proto_depIdxs,
		MessageInfos:      file_standort_v2_service_proto_msgTypes,
	}.Build()
	File_standort_v2_service_proto = out.File
	file_standort_v2_service_proto_goTypes = nil
	file_standort_v2_service_proto_depIdxs = nil
}
