# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: standort/v1/service.proto for package 'Standort.V1'

require 'grpc'
require 'standort/v1/service_pb'

module Standort
  module V1
    module Service
      # Service allows to get locations by different filters.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'standort.v1.Service'

        # GetLocationByIP for an IP address.
        rpc :GetLocationByIP, ::Standort::V1::GetLocationByIPRequest, ::Standort::V1::GetLocationByIPResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
