# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: standort/v1/service.proto

require 'google/protobuf'


descriptor_data = "\n\x19standort/v1/service.proto\x12\x0bstandort.v1\"B\n\x08Location\x12\x18\n\x07\x63ountry\x18\x01 \x01(\tR\x07\x63ountry\x12\x1c\n\tcontinent\x18\x02 \x01(\tR\tcontinent\"(\n\x16GetLocationByIPRequest\x12\x0e\n\x02ip\x18\x01 \x01(\tR\x02ip\"\xc9\x01\n\x17GetLocationByIPResponse\x12\x42\n\x04meta\x18\x01 \x03(\x0b\x32..standort.v1.GetLocationByIPResponse.MetaEntryR\x04meta\x12\x31\n\x08location\x18\x02 \x01(\x0b\x32\x15.standort.v1.LocationR\x08location\x1a\x37\n\tMetaEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"@\n\x1aGetLocationByLatLngRequest\x12\x10\n\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n\x03lng\x18\x02 \x01(\x01R\x03lng\"\xd1\x01\n\x1bGetLocationByLatLngResponse\x12\x46\n\x04meta\x18\x02 \x03(\x0b\x32\x32.standort.v1.GetLocationByLatLngResponse.MetaEntryR\x04meta\x12\x31\n\x08location\x18\x01 \x01(\x0b\x32\x15.standort.v1.LocationR\x08location\x1a\x37\n\tMetaEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x32\xd5\x01\n\x07Service\x12^\n\x0fGetLocationByIP\x12#.standort.v1.GetLocationByIPRequest\x1a$.standort.v1.GetLocationByIPResponse\"\x00\x12j\n\x13GetLocationByLatLng\x12\'.standort.v1.GetLocationByLatLngRequest\x1a(.standort.v1.GetLocationByLatLngResponse\"\x00\x42\x45Z4github.com/alexfalkowski/standort/v2/api/standort/v1\xea\x02\x0cStandort::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Standort
  module V1
    Location = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("standort.v1.Location").msgclass
    GetLocationByIPRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("standort.v1.GetLocationByIPRequest").msgclass
    GetLocationByIPResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("standort.v1.GetLocationByIPResponse").msgclass
    GetLocationByLatLngRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("standort.v1.GetLocationByLatLngRequest").msgclass
    GetLocationByLatLngResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("standort.v1.GetLocationByLatLngResponse").msgclass
  end
end
