#!/usr/bin/env bash

set -e

latest_tag=$(git tag | sort -V | tail -1)

# Build and push docker.
docker build -t alexfalkowski/standort:"$latest_tag" .
docker push alexfalkowski/standort:"$latest_tag"
